apiVersion: v1
kind: Service
metadata:
  name: lanchonete-producao-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: lanchonete-producao
