apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lanchonete-producao
  template:
    metadata:
      labels:
        app: lanchonete-producao
    spec:
      containers:
        - name: lanchonete-producao-container
          image: lanchonete-producao:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY

